name: Deploy to Release Branch

# Run workflow on every push to the master branch
on:
  push:
    branches: [ main ]

jobs:
  deploy-blazor-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v2
    
    # sets up .NET Core SDK
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'

    # - name: Install .NET WASM Build Tools
    #   run: dotnet workload install wasm-tools

    # publishes Blazor project to the release-folder
    - name: Publish Blazor Project
      run: dotnet publish jnmechanical.services.csproj -c Release -o release --nologo

    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Go away Jekyll
      run: touch release/wwwroot/.nojekyll
      
    - name: Commit wwwroot to Release Branch
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: release
        FOLDER: release/wwwroot
